[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate", "yarn run build"]

[start]
cmd = "yarn run start:prod" 